# Generated by Django 4.2.5 on 2023-10-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default='2023-01-01', verbose_name='Last authentication'),
        ),
    ]
