version: '3'

services:

  redis:
    image: redis
    ports:
      - '6379:6379'

  db:
    image: postgres
    env_file:
      - .env
    environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    tty: true
    command: sh -c "sleep 3 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: sh -c "sleep 10 && celery -A config worker -l INFO"
    volumes:
      - .:/code
    depends_on:
      - redis

  celery_beat:
    build: .
    tty: true
    command: sh -c "sleep 11 && celery -A config beat -l info -S django"
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  postgres_data: