# Generated by Django 4.2.5 on 2023-10-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Course name')),
                ('description', models.TextField(verbose_name='Description')),
                ('preview_pic', models.ImageField(blank=True, null=True, upload_to='course_pictures/', verbose_name='Picture')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Lesson name')),
                ('description', models.TextField(verbose_name='Description')),
                ('preview_pic', models.ImageField(blank=True, null=True, upload_to='lesson_pictures/', verbose_name='Picture')),
                ('url', models.URLField(max_length=1000, verbose_name='Url')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
    ]
