# Generated by Django 4.2.5 on 2023-10-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_course_description_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'afterpay'), ('card', 'card')], default='card', max_length=30, verbose_name='Payment options'),
        ),
    ]
